#!/usr/bin/env node
/**
 * md2html.js — DeepWiki Markdown to HTML Converter
 *
 * Converts the Markdown output generated by the DeepWiki skill into a
 * standalone HTML file using the deepwiki-template.html.
 *
 * Usage:
 *   node md2html.js <input.md> [output.html] [--repo-owner=NAME] [--repo-name=NAME]
 *
 * If output.html is omitted, the filename is derived from the input.
 * Dependencies: none (uses only Node.js built-ins).
 */

const fs = require('fs');
const path = require('path');

// ─── CLI args ──────────────────────────────────────────────
const args = process.argv.slice(2);
const flags = {};
const positional = [];

args.forEach(a => {
    if (a.startsWith('--')) {
        const [k, v] = a.slice(2).split('=');
        flags[k] = v || true;
    } else {
        positional.push(a);
    }
});

const inputFile = positional[0];
const outputFile = positional[1] || inputFile.replace(/\.md$/i, '.html');
const repoOwner = flags['repo-owner'] || 'Project';
const repoName = flags['repo-name'] || path.basename(inputFile, '.md');

if (!inputFile) {
    console.error('Usage: node md2html.js <input.md> [output.html] [--repo-owner=X] [--repo-name=Y]');
    process.exit(1);
}

const templateDir = __dirname;
const templateFile = path.join(templateDir, 'deepwiki-template.html');

if (!fs.existsSync(templateFile)) {
    console.error(`Template not found: ${templateFile}`);
    process.exit(1);
}

const md = fs.readFileSync(inputFile, 'utf8');
const template = fs.readFileSync(templateFile, 'utf8');

// ─── Helpers ──────────────────────────────────────────────
function escapeHtml(s) {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}

function slugify(text) {
    return text.toLowerCase().replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').trim();
}

// ─── Parse navigation block ──────────────────────────────
function extractNavigation(md) {
    const navMatch = md.match(/##\s*📑\s*Navigation\s*\n([\s\S]*?)(?=\n---|\n## (?!📑)|\n# )/);
    if (!navMatch) return { navHtml: '', mdWithoutNav: md };

    const navBlock = navMatch[1];
    const mdWithoutNav = md.replace(navMatch[0], '');

    let html = '';
    const lines = navBlock.split('\n').filter(l => l.trim());

    lines.forEach(line => {
        const indent = (line.match(/^\s*/)[0].length) / 2;
        const text = line.replace(/^\s*[-*]\s*/, '').replace(/\*\*/g, '').trim();
        if (!text) return;

        const pageId = 'page-' + slugify(text);

        if (indent === 0) {
            html += `<div class="nav-section">`;
            html += `<a class="nav-item" data-page="${pageId}" onclick="navigateTo('${pageId}')">
                <svg class="nav-icon" viewBox="0 0 16 16" fill="currentColor"><path d="M1.75 1h8.5c.966 0 1.75.784 1.75 1.75v5.5A1.75 1.75 0 0 1 10.25 10H7.061l-2.574 2.573A1.458 1.458 0 0 1 2 11.543V10h-.25A1.75 1.75 0 0 1 0 8.25v-5.5C0 1.784.784 1 1.75 1ZM1.5 2.75v5.5c0 .138.112.25.25.25h1a.75.75 0 0 1 .75.75v2.19l2.72-2.72a.749.749 0 0 1 .53-.22h3.5a.25.25 0 0 0 .25-.25v-5.5a.25.25 0 0 0-.25-.25h-8.5a.25.25 0 0 0-.25.25Z"/></svg>
                ${escapeHtml(text)}
            </a></div>\n`;
        } else if (indent === 1) {
            // Check if this is last item before a deeper level
            html += `<div class="nav-section"><a class="nav-item" data-page="${pageId}" onclick="navigateTo('${pageId}')" style="padding-left:${16 + indent * 20}px">
                ${escapeHtml(text)}
            </a></div>\n`;
        } else {
            html += `<div class="nav-section"><a class="nav-item" data-page="${pageId}" onclick="navigateTo('${pageId}')" style="padding-left:${16 + indent * 20}px; font-size:0.8rem">
                ${escapeHtml(text)}
            </a></div>\n`;
        }
    });

    return { navHtml: html, mdWithoutNav };
}

// ─── Convert Markdown to HTML (lightweight) ──────────────
function mdToHtml(text) {
    let html = text;

    // Convert [quote][mermaid]...[/mermaid][/quote] to <div class="mermaid">
    html = html.replace(/\[quote\]\[mermaid\]\s*([\s\S]*?)\s*\[\/mermaid\]\[\/quote\]/g,
        (_, code) => `<div class="mermaid">\n${code.trim()}\n</div>`);

    // Fenced code blocks ```lang ... ```
    html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_, lang, code) => {
        const cls = lang ? ` class="language-${lang}"` : '';
        return `<pre><code${cls}>${escapeHtml(code.trimEnd())}</code></pre>`;
    });

    // Indented code blocks (4+ spaces)
    html = html.replace(/(?:^|\n)((?:    .+\n?)+)/g, (_, block) => {
        const code = block.replace(/^    /gm, '');
        return `\n<pre><code>${escapeHtml(code.trimEnd())}</code></pre>\n`;
    });

    // Tables
    html = html.replace(/((?:\|.*\|\n)+)/g, (_, tableBlock) => {
        const rows = tableBlock.trim().split('\n');
        if (rows.length < 2) return tableBlock;

        const headerCells = rows[0].split('|').filter(c => c.trim()).map(c => c.trim());
        // Skip separator row (row[1])
        const bodyRows = rows.slice(2);

        let thtml = '<table><thead><tr>';
        headerCells.forEach(c => thtml += `<th>${inlineFormat(c)}</th>`);
        thtml += '</tr></thead><tbody>';
        bodyRows.forEach(row => {
            const cells = row.split('|').filter(c => c.trim()).map(c => c.trim());
            thtml += '<tr>';
            cells.forEach(c => thtml += `<td>${inlineFormat(c)}</td>`);
            thtml += '</tr>';
        });
        thtml += '</tbody></table>';
        return thtml;
    });

    // Blockquotes
    html = html.replace(/((?:^>.*\n?)+)/gm, (_, block) => {
        const inner = block.replace(/^>\s?/gm, '');
        return `<blockquote>${inlineFormat(inner.trim())}</blockquote>\n`;
    });

    // Headings
    html = html.replace(/^#### (.+)$/gm, (_, t) => `<h4 id="${slugify(t)}">${inlineFormat(t)}</h4>`);
    html = html.replace(/^### (.+)$/gm, (_, t) => `<h3 id="${slugify(t)}">${inlineFormat(t)}</h3>`);
    html = html.replace(/^## (.+)$/gm, (_, t) => `<h2 id="${slugify(t)}">${inlineFormat(t)}</h2>`);
    html = html.replace(/^# (.+)$/gm, (_, t) => `<h1 id="${slugify(t)}">${inlineFormat(t)}</h1>`);

    // Unordered lists
    html = html.replace(/((?:^[\t ]*[-*]\s+.+\n?)+)/gm, (_, block) => {
        const items = block.split('\n').filter(l => l.trim());
        let list = '<ul>';
        items.forEach(item => {
            const text = item.replace(/^[\t ]*[-*]\s+/, '');
            list += `<li>${inlineFormat(text)}</li>`;
        });
        list += '</ul>';
        return list;
    });

    // Ordered lists
    html = html.replace(/((?:^\d+\.\s+.+\n?)+)/gm, (_, block) => {
        const items = block.split('\n').filter(l => l.trim());
        let list = '<ol>';
        items.forEach(item => {
            const text = item.replace(/^\d+\.\s+/, '');
            list += `<li>${inlineFormat(text)}</li>`;
        });
        list += '</ol>';
        return list;
    });

    // Horizontal rules → page separators
    html = html.replace(/^---\s*$/gm, '<hr>');

    // Paragraphs - wrap remaining text lines
    html = html.replace(/^(?!<[a-z/])((?:[^\n<].+\n?)+)/gm, (_, block) => {
        const trimmed = block.trim();
        if (!trimmed) return '';
        return `<p>${inlineFormat(trimmed)}</p>\n`;
    });

    return html;
}

// ─── Inline formatting ───────────────────────────────────
function inlineFormat(text) {
    // Bold
    text = text.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    // Italic
    text = text.replace(/\*(.+?)\*/g, '<em>$1</em>');
    // Inline code
    text = text.replace(/`([^`]+)`/g, '<code>$1</code>');
    // Links [text](url)
    text = text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>');
    // Emoji indicators
    text = text.replace(/📄/g, '<span style="margin-right:4px">📄</span>');
    // Line breaks
    text = text.replace(/\n/g, '<br>');
    return text;
}

// ─── Split into wiki pages ───────────────────────────────
function splitIntoPages(html) {
    // Split on <hr> or on <h1> tags
    const parts = html.split(/<hr\s*\/?>/);
    const pages = [];

    parts.forEach((part, i) => {
        const trimmed = part.trim();
        if (!trimmed) return;

        // Try to extract the first heading as page title
        const titleMatch = trimmed.match(/<h[12][^>]*>(.+?)<\/h[12]>/);
        const title = titleMatch ? titleMatch[1].replace(/<[^>]+>/g, '') : `Page ${i + 1}`;
        const pageId = 'page-' + slugify(title);

        pages.push({ id: pageId, title, html: trimmed });
    });

    return pages;
}

// ─── Build TOC from headings ─────────────────────────────
function buildTocHtml(pages) {
    // TOC is built dynamically via JS in the template, but we pre-generate
    // initial links for the first page's headings
    if (pages.length === 0) return '';

    const firstPage = pages[0].html;
    const headings = [...firstPage.matchAll(/<(h[23])\s+id="([^"]+)"[^>]*>(.+?)<\/\1>/g)];
    let toc = '';
    headings.forEach(m => {
        const depth = m[1] === 'h3' ? ' depth-3' : '';
        const id = m[2];
        const text = m[3].replace(/<[^>]+>/g, '');
        toc += `<a class="toc-link${depth}" href="#${id}">${escapeHtml(text)}</a>\n`;
    });
    return toc;
}

// ─── Main pipeline ───────────────────────────────────────
const { navHtml, mdWithoutNav } = extractNavigation(md);
const contentHtml = mdToHtml(mdWithoutNav);
const pages = splitIntoPages(contentHtml);

// Build page HTML
let pagesHtml = '';
pages.forEach((p, i) => {
    const activeClass = i === 0 ? ' active' : '';
    pagesHtml += `<div class="wiki-page${activeClass}" id="${p.id}">\n${p.html}\n</div>\n`;
});

// Build nav HTML (if no nav was in the MD, generate from page titles)
let finalNavHtml = navHtml;
if (!finalNavHtml.trim()) {
    finalNavHtml = pages.map(p =>
        `<div class="nav-section"><a class="nav-item${p === pages[0] ? ' active' : ''}" data-page="${p.id}" onclick="navigateTo('${p.id}')">
            <svg class="nav-icon" viewBox="0 0 16 16" fill="currentColor"><path d="M0 1.75A.75.75 0 0 1 .75 1h4.253c1.227 0 2.317.59 3 1.501A3.743 3.743 0 0 1 11.006 1h4.245a.75.75 0 0 1 .75.75v10.5a.75.75 0 0 1-.75.75h-4.507a2.25 2.25 0 0 0-1.591.659l-.622.621a.75.75 0 0 1-1.06 0l-.622-.621A2.25 2.25 0 0 0 5.258 13H.75a.75.75 0 0 1-.75-.75Zm7.251 10.324.004-5.073-.002-2.253A2.25 2.25 0 0 0 5.003 2.5H1.5v9h3.757a3.75 3.75 0 0 1 1.994.574ZM8.755 4.75l-.004 7.322a3.752 3.752 0 0 1 1.992-.572H14.5v-9h-3.495a2.25 2.25 0 0 0-2.25 2.25Z"/></svg>
            ${escapeHtml(p.title)}
        </a></div>`
    ).join('\n');
}

const tocHtml = buildTocHtml(pages);

// Inject into template
let output = template
    .replace(/\{\{REPO_OWNER\}\}/g, escapeHtml(repoOwner))
    .replace(/\{\{REPO_NAME\}\}/g, escapeHtml(repoName))
    .replace('{{NAV_ITEMS}}', finalNavHtml)
    .replace('{{PAGE_CONTENT}}', pagesHtml)
    .replace('{{TOC_ITEMS}}', tocHtml);

fs.writeFileSync(outputFile, output, 'utf8');
console.log(`✅ Generated: ${outputFile}`);
console.log(`   Pages: ${pages.length}`);
console.log(`   Navigation items: ${finalNavHtml.split('nav-item').length - 1}`);
